// Auto-generated by scripts/generate-ai-types.ts
// Do not edit manually - run 'pnpm generate:ai-types' to regenerate

export function generateTypeDefinitions(): string {
  return `type IntentModel = {
  meta: { version: string; project: string; lastUpdated: string; status: 'draft' | 'in_review' | 'approved' }
  actors: Actor[]
  entities: Entity[]
  journeys: Journey[]
  businessRules: BusinessRule[]
  constraints: Constraint[]
  openQuestions: OpenQuestion[]
}

type Actor = {
  id: string          // short lowercase, e.g. 'lsp', 'acfs', 'p4tc'
  name: string
  description: string
  auth: string
  responsibilities: { id: string; description: string; warn?: string; edge?: string }[]
  // responsibility IDs follow pattern: actorId:rN (e.g. 'wff:r1')
  deferred?: boolean
}

type Entity = {
  id: string
  name: string
  description: string
  key_fields: { name: string; type: string; description: string; warn?: string }[]
  lifecycle: {
    states: string[]
    transitions: { from: string; to: string; trigger: string; guard?: string; warn?: string }[]
  }
  is_integration?: boolean
  deferred?: boolean
}

type Journey = {
  id: string           // kebab-case, e.g. 'carrier-books-pickup'
  name: string
  primary_actor: string  // must reference an existing actor ID
  preconditions: string[]
  steps: { order: number; title: string; detail: string; precondition?: string; warn?: string; edge?: string }[]
  success_outcome: string
  warn?: string
  deferred?: boolean
}

type BusinessRule = {
  id: string           // pattern: 'BR-NNN'
  description: string
  applies_to: string[] // must reference existing actor or entity IDs
  source: string
  warn?: string
}

type Constraint = {
  id: string           // pattern: 'C-NNN'
  constraint: string
  type: 'capacity' | 'pricing' | 'access' | 'compliance' | 'temporal' | 'admin' | 'platform' | 'notification'
}

type OpenQuestion = {
  id: string           // pattern: 'OQ-NNN'
  question: string
  reason: string
  status: 'open' | 'deferred' | 'resolved'
  resolution?: string
}
`
}
