import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join, resolve } from 'node:path'
import type { IntentModel, Entity } from '@/domain/intent-model/types'

const PORTAL_DIR = resolve(process.cwd(), '../vbs-portal')
const CONTRACT_PATH = join(PORTAL_DIR, 'src/lib/intent-contract.ts')
const CHECKLIST_PATH = join(PORTAL_DIR, 'docs/intent-contract-rules-checklist.md')

function loadExistingVerified(): Map<string, boolean> {
  const map = new Map<string, boolean>()
  if (!existsSync(CONTRACT_PATH)) return map

  const content = readFileSync(CONTRACT_PATH, 'utf-8')
  const rulesSection = content.slice(content.indexOf('contractRules'))
  if (!rulesSection) return map

  const ruleRegex = /id:\s*["']([^"']+)["'][\s\S]*?verified:\s*(true|false)/g
  let match
  while ((match = ruleRegex.exec(rulesSection)) !== null) {
    map.set(match[1], match[2] === 'true')
  }

  return map
}

function isIntegrationEntity(entity: Entity): boolean {
  return entity.is_integration === true || entity.id.startsWith('integration_')
}

function generateContract(model: IntentModel): string {
  const existingVerified = loadExistingVerified()
  const domainEntities = model.entities.filter(e => !isIntegrationEntity(e))

  const entitiesStr = domainEntities.map(e => {
    const fields = e.key_fields.map(f => {
      const warn = f.warn ? `\n      warn: ${JSON.stringify(f.warn)},` : ''
      return `    {
      name: ${JSON.stringify(f.name)},
      type: ${JSON.stringify(f.type)},
      description: ${JSON.stringify(f.description)},${warn}
    }`
    }).join(',\n')

    const states = e.lifecycle.states.map(s => `'${s}'`).join(', ')

    const transitions = e.lifecycle.transitions.map(t => {
      const guard = t.guard ? `\n      guard: ${JSON.stringify(t.guard)},` : ''
      const warn = t.warn ? `\n      warn: ${JSON.stringify(t.warn)},` : ''
      return `    {
      from: ${JSON.stringify(t.from)},
      to: ${JSON.stringify(t.to)},
      trigger: ${JSON.stringify(t.trigger)},${guard}${warn}
    }`
    }).join(',\n')

    return `  {
    id: ${JSON.stringify(e.id)},
    name: ${JSON.stringify(e.name)},
    description: ${JSON.stringify(e.description)},
    fields: [
${fields}
    ],
    states: [${states}],
    transitions: [
${transitions}
    ],
  }`
  }).join(',\n')

  const rulesStr = model.businessRules.map(r => {
    const verified = existingVerified.get(r.id) ?? false
    const appliesTo = r.applies_to.map(a => `'${a}'`).join(', ')
    return `  {
    id: ${JSON.stringify(r.id)},
    description: ${JSON.stringify(r.description)},
    applies_to: [${appliesTo}],
    source: ${JSON.stringify(r.source)},
    verified: ${verified},
  }`
  }).join(',\n')

  return `// AUTO-GENERATED by vbs-intent/scripts/export-contract.ts
// Do not edit manually except for \`verified\` fields on rules.
// Re-run: cd ../vbs-intent && pnpm run export:contract

export type ContractMeta = {
  version: string
  project: string
  exportDate: string
  modelStatus: 'draft' | 'in_review' | 'approved'
}

export type ContractField = {
  name: string
  type: string
  description: string
  warn?: string
}

export type ContractTransition = {
  from: string
  to: string
  trigger: string
  guard?: string
  warn?: string
}

export type ContractEntity = {
  id: string
  name: string
  description: string
  fields: ContractField[]
  states: string[]
  transitions: ContractTransition[]
}

export type ContractRule = {
  id: string
  description: string
  applies_to: string[]
  source: string
  verified: boolean
}

export const contractMeta: ContractMeta = {
  version: ${JSON.stringify(model.meta.version)},
  project: ${JSON.stringify(model.meta.project)},
  exportDate: '${new Date().toISOString().split('T')[0]}',
  modelStatus: ${JSON.stringify(model.meta.status)},
}

export const contractEntities: ContractEntity[] = [
${entitiesStr}
]

export const contractRules: ContractRule[] = [
${rulesStr}
]
`
}

function generateChecklist(model: IntentModel): string {
  const lines = [
    '# Intent Model Business Rules Checklist',
    '',
    `Version: ${model.meta.version} | Generated: ${new Date().toISOString().split('T')[0]}`,
    '',
    '| Status | ID | Description | Applies To | Source |',
    '|---|---|---|---|---|',
  ]

  for (const rule of model.businessRules) {
    const appliesTo = rule.applies_to.join(', ')
    lines.push(`| [ ] | ${rule.id} | ${rule.description} | ${appliesTo} | ${rule.source} |`)
  }

  return lines.join('\n') + '\n'
}

/**
 * Export the intent model as a contract to the portal repo.
 * Called by the CLI script and the API apply route.
 * Returns true if the portal directory exists and export succeeded.
 */
export function exportContract(model: IntentModel): boolean {
  if (!existsSync(PORTAL_DIR)) return false

  const contract = generateContract(model)
  writeFileSync(CONTRACT_PATH, contract, 'utf-8')

  const checklist = generateChecklist(model)
  writeFileSync(CHECKLIST_PATH, checklist, 'utf-8')

  return true
}
